package com.alpha.todolist.presentation.theme

import androidx.compose.ui.graphics.Color


//Light
val primaryLight = Color(0xFF002068)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFF1D41A0)
val onPrimaryContainerLight = Color(0xFFDCE2FF)
val secondaryLight = Color(0xFF535D83)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFD1D9FF)
val onSecondaryContainerLight = Color(0xFF374266)
val tertiaryLight = Color(0xFF44005B)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFF6B2983)
val onTertiaryContainerLight = Color(0xFFF9D6FF)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF410002)
val backgroundLight = Color(0xFFFAF8FF)
val onBackgroundLight = Color(0xFF1A1B21)
val surfaceLight = Color(0xFFFAF8FF)
val onSurfaceLight = Color(0xFF1A1B21)
val surfaceVariantLight = Color(0xFFE0E1F1)
val onSurfaceVariantLight = Color(0xFF444652)
val outlineLight = Color(0xFF747684)
val outlineVariantLight = Color(0xFFC4C5D4)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF2F3037)
val inverseOnSurfaceLight = Color(0xFFF1F0F8)
val inversePrimaryLight = Color(0xFFB5C4FF)
val surfaceDimLight = Color(0xFFDAD9E2)
val surfaceBrightLight = Color(0xFFFAF8FF)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFF4F3FB)
val surfaceContainerLight = Color(0xFFEEEDF6)
val surfaceContainerHighLight = Color(0xFFE8E7F0)
val surfaceContainerHighestLight = Color(0xFFE3E1EA)




//LightMediumContrast
val primaryLightMediumContrast = Color(0xFF002068)
val onPrimaryLightMediumContrast = Color(0xFFFFFFFF)
val primaryContainerLightMediumContrast = Color(0xFF1D41A0)
val onPrimaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val secondaryLightMediumContrast = Color(0xFF374166)
val onSecondaryLightMediumContrast = Color(0xFFFFFFFF)
val secondaryContainerLightMediumContrast = Color(0xFF69739A)
val onSecondaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val tertiaryLightMediumContrast = Color(0xFF44005B)
val onTertiaryLightMediumContrast = Color(0xFFFFFFFF)
val tertiaryContainerLightMediumContrast = Color(0xFF6B2983)
val onTertiaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val errorLightMediumContrast = Color(0xFF8C0009)
val onErrorLightMediumContrast = Color(0xFFFFFFFF)
val errorContainerLightMediumContrast = Color(0xFFDA342E)
val onErrorContainerLightMediumContrast = Color(0xFFFFFFFF)
val backgroundLightMediumContrast = Color(0xFFFAF8FF)
val onBackgroundLightMediumContrast = Color(0xFF1A1B21)
val surfaceLightMediumContrast = Color(0xFFFAF8FF)
val onSurfaceLightMediumContrast = Color(0xFF1A1B21)
val surfaceVariantLightMediumContrast = Color(0xFFE0E1F1)
val onSurfaceVariantLightMediumContrast = Color(0xFF40424E)
val outlineLightMediumContrast = Color(0xFF5C5E6B)
val outlineVariantLightMediumContrast = Color(0xFF787A87)
val scrimLightMediumContrast = Color(0xFF000000)
val inverseSurfaceLightMediumContrast = Color(0xFF2F3037)
val inverseOnSurfaceLightMediumContrast = Color(0xFFF1F0F8)
val inversePrimaryLightMediumContrast = Color(0xFFB5C4FF)
val surfaceDimLightMediumContrast = Color(0xFFDAD9E2)
val surfaceBrightLightMediumContrast = Color(0xFFFAF8FF)
val surfaceContainerLowestLightMediumContrast = Color(0xFFFFFFFF)
val surfaceContainerLowLightMediumContrast = Color(0xFFF4F3FB)
val surfaceContainerLightMediumContrast = Color(0xFFEEEDF6)
val surfaceContainerHighLightMediumContrast = Color(0xFFE8E7F0)
val surfaceContainerHighestLightMediumContrast = Color(0xFFE3E1EA)


//LightHighContrast
val primaryLightHighContrast = Color(0xFF001C5D)
val onPrimaryLightHighContrast = Color(0xFFFFFFFF)
val primaryContainerLightHighContrast = Color(0xFF143B9A)
val onPrimaryContainerLightHighContrast = Color(0xFFFFFFFF)
val secondaryLightHighContrast = Color(0xFF152043)
val onSecondaryLightHighContrast = Color(0xFFFFFFFF)
val secondaryContainerLightHighContrast = Color(0xFF374166)
val onSecondaryContainerLightHighContrast = Color(0xFFFFFFFF)
val tertiaryLightHighContrast = Color(0xFF3D0052)
val onTertiaryLightHighContrast = Color(0xFFFFFFFF)
val tertiaryContainerLightHighContrast = Color(0xFF66247D)
val onTertiaryContainerLightHighContrast = Color(0xFFFFFFFF)
val errorLightHighContrast = Color(0xFF4E0002)
val onErrorLightHighContrast = Color(0xFFFFFFFF)
val errorContainerLightHighContrast = Color(0xFF8C0009)
val onErrorContainerLightHighContrast = Color(0xFFFFFFFF)
val backgroundLightHighContrast = Color(0xFFFAF8FF)
val onBackgroundLightHighContrast = Color(0xFF1A1B21)
val surfaceLightHighContrast = Color(0xFFFAF8FF)
val onSurfaceLightHighContrast = Color(0xFF000000)
val surfaceVariantLightHighContrast = Color(0xFFE0E1F1)
val onSurfaceVariantLightHighContrast = Color(0xFF21232E)
val outlineLightHighContrast = Color(0xFF40424E)
val outlineVariantLightHighContrast = Color(0xFF40424E)
val scrimLightHighContrast = Color(0xFF000000)
val inverseSurfaceLightHighContrast = Color(0xFF2F3037)
val inverseOnSurfaceLightHighContrast = Color(0xFFFFFFFF)
val inversePrimaryLightHighContrast = Color(0xFFE9EBFF)
val surfaceDimLightHighContrast = Color(0xFFDAD9E2)
val surfaceBrightLightHighContrast = Color(0xFFFAF8FF)
val surfaceContainerLowestLightHighContrast = Color(0xFFFFFFFF)
val surfaceContainerLowLightHighContrast = Color(0xFFF4F3FB)
val surfaceContainerLightHighContrast = Color(0xFFEEEDF6)
val surfaceContainerHighLightHighContrast = Color(0xFFE8E7F0)
val surfaceContainerHighestLightHighContrast = Color(0xFFE3E1EA)


//Dark
val primaryDark = Color(0xFFB5C4FF)
val onPrimaryDark = Color(0xFF00287C)
val primaryContainerDark = Color(0xFF00287C)
val onPrimaryContainerDark = Color(0xFFAABCFF)
val secondaryDark = Color(0xFFBBC5F1)
val onSecondaryDark = Color(0xFF242F52)
val secondaryContainerDark = Color(0xFF313C60)
val onSecondaryContainerDark = Color(0xFFC5CFFC)
val tertiaryDark = Color(0xFFEEB0FF)
val onTertiaryDark = Color(0xFF510A69)
val tertiaryContainerDark = Color(0xFF510B6A)
val onTertiaryContainerDark = Color(0xFFEBA5FF)
val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF93000A)
val onErrorContainerDark = Color(0xFFFFDAD6)
val backgroundDark = Color(0xFF121319)
val onBackgroundDark = Color(0xFFE3E1EA)
val surfaceDark = Color(0xFF121319)
val onSurfaceDark = Color(0xFFE3E1EA)
val surfaceVariantDark = Color(0xFF444652)
val onSurfaceVariantDark = Color(0xFFC4C5D4)
val outlineDark = Color(0xFF8E909E)
val outlineVariantDark = Color(0xFF444652)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFE3E1EA)
val inverseOnSurfaceDark = Color(0xFF2F3037)
val inversePrimaryDark = Color(0xFF3858B7)
val surfaceDimDark = Color(0xFF121319)
val surfaceBrightDark = Color(0xFF38393F)
val surfaceContainerLowestDark = Color(0xFF0D0E14)
val surfaceContainerLowDark = Color(0xFF1A1B21)
val surfaceContainerDark = Color(0xFF1E1F25)
val surfaceContainerHighDark = Color(0xFF282A30)
val surfaceContainerHighestDark = Color(0xFF33343B)


//DarkMediumContrast
val primaryDarkMediumContrast = Color(0xFFBBC9FF)
val onPrimaryDarkMediumContrast = Color(0xFF001242)
val primaryContainerDarkMediumContrast = Color(0xFF6E8CEE)
val onPrimaryContainerDarkMediumContrast = Color(0xFF000000)
val secondaryDarkMediumContrast = Color(0xFFBFC9F5)
val onSecondaryDarkMediumContrast = Color(0xFF081436)
val secondaryContainerDarkMediumContrast = Color(0xFF858FB8)
val onSecondaryContainerDarkMediumContrast = Color(0xFF000000)
val tertiaryDarkMediumContrast = Color(0xFFF0B7FF)
val onTertiaryDarkMediumContrast = Color(0xFF2B003A)
val tertiaryContainerDarkMediumContrast = Color(0xFFBC75D3)
val onTertiaryContainerDarkMediumContrast = Color(0xFF000000)
val errorDarkMediumContrast = Color(0xFFFFBAB1)
val onErrorDarkMediumContrast = Color(0xFF370001)
val errorContainerDarkMediumContrast = Color(0xFFFF5449)
val onErrorContainerDarkMediumContrast = Color(0xFF000000)
val backgroundDarkMediumContrast = Color(0xFF121319)
val onBackgroundDarkMediumContrast = Color(0xFFE3E1EA)
val surfaceDarkMediumContrast = Color(0xFF121319)
val onSurfaceDarkMediumContrast = Color(0xFFFCFAFF)
val surfaceVariantDarkMediumContrast = Color(0xFF444652)
val onSurfaceVariantDarkMediumContrast = Color(0xFFC9CAD8)
val outlineDarkMediumContrast = Color(0xFFA0A2B0)
val outlineVariantDarkMediumContrast = Color(0xFF808290)
val scrimDarkMediumContrast = Color(0xFF000000)
val inverseSurfaceDarkMediumContrast = Color(0xFFE3E1EA)
val inverseOnSurfaceDarkMediumContrast = Color(0xFF292A30)
val inversePrimaryDarkMediumContrast = Color(0xFF1C409F)
val surfaceDimDarkMediumContrast = Color(0xFF121319)
val surfaceBrightDarkMediumContrast = Color(0xFF38393F)
val surfaceContainerLowestDarkMediumContrast = Color(0xFF0D0E14)
val surfaceContainerLowDarkMediumContrast = Color(0xFF1A1B21)
val surfaceContainerDarkMediumContrast = Color(0xFF1E1F25)
val surfaceContainerHighDarkMediumContrast = Color(0xFF282A30)
val surfaceContainerHighestDarkMediumContrast = Color(0xFF33343B)


//DarkHighContrast
val primaryDarkHighContrast = Color(0xFFFCFAFF)
val onPrimaryDarkHighContrast = Color(0xFF000000)
val primaryContainerDarkHighContrast = Color(0xFFBBC9FF)
val onPrimaryContainerDarkHighContrast = Color(0xFF000000)
val secondaryDarkHighContrast = Color(0xFFFCFAFF)
val onSecondaryDarkHighContrast = Color(0xFF000000)
val secondaryContainerDarkHighContrast = Color(0xFFBFC9F5)
val onSecondaryContainerDarkHighContrast = Color(0xFF000000)
val tertiaryDarkHighContrast = Color(0xFFFFF9FA)
val onTertiaryDarkHighContrast = Color(0xFF000000)
val tertiaryContainerDarkHighContrast = Color(0xFFF0B7FF)
val onTertiaryContainerDarkHighContrast = Color(0xFF000000)
val errorDarkHighContrast = Color(0xFFFFF9F9)
val onErrorDarkHighContrast = Color(0xFF000000)
val errorContainerDarkHighContrast = Color(0xFFFFBAB1)
val onErrorContainerDarkHighContrast = Color(0xFF000000)
val backgroundDarkHighContrast = Color(0xFF121319)
val onBackgroundDarkHighContrast = Color(0xFFE3E1EA)
val surfaceDarkHighContrast = Color(0xFF121319)
val onSurfaceDarkHighContrast = Color(0xFFFFFFFF)
val surfaceVariantDarkHighContrast = Color(0xFF444652)
val onSurfaceVariantDarkHighContrast = Color(0xFFFCFAFF)
val outlineDarkHighContrast = Color(0xFFC9CAD8)
val outlineVariantDarkHighContrast = Color(0xFFC9CAD8)
val scrimDarkHighContrast = Color(0xFF000000)
val inverseSurfaceDarkHighContrast = Color(0xFFE3E1EA)
val inverseOnSurfaceDarkHighContrast = Color(0xFF000000)
val inversePrimaryDarkHighContrast = Color(0xFF00236E)
val surfaceDimDarkHighContrast = Color(0xFF121319)
val surfaceBrightDarkHighContrast = Color(0xFF38393F)
val surfaceContainerLowestDarkHighContrast = Color(0xFF0D0E14)
val surfaceContainerLowDarkHighContrast = Color(0xFF1A1B21)
val surfaceContainerDarkHighContrast = Color(0xFF1E1F25)
val surfaceContainerHighDarkHighContrast = Color(0xFF282A30)
val surfaceContainerHighestDarkHighContrast = Color(0xFF33343B)







